# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-07 18:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sce_name', models.CharField(default='', max_length=30, verbose_name='场景名称')),
                ('sce_id', models.CharField(default='', max_length=255, verbose_name='场景识别码')),
                ('sce_info', models.TextField(default='', verbose_name='场景描述')),
                ('devnum', models.IntegerField(default=0, verbose_name='设备数量')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2019, 7, 7, 18, 1, 10, 226674), null=True, verbose_name='接入时间')),
                ('sce_pri', models.IntegerField(default=0, verbose_name='优先级')),
                ('sce_area', models.FloatField(default=0, verbose_name='管理面积')),
            ],
        ),
    ]
