# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-07 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SceneApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='sce_passwd',
            field=models.CharField(default='', max_length=255, verbose_name='场景密码'),
        ),
        migrations.AddField(
            model_name='scene',
            name='sce_status',
            field=models.IntegerField(choices=[(1, '在线'), (2, '离线')], default=2, verbose_name='场景状态'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 7, 23, 8, 50, 941505), null=True, verbose_name='接入时间'),
        ),
    ]
