# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-06 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30, verbose_name='用户名')),
                ('passwd', models.CharField(default='', max_length=255, verbose_name='用户密码')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=20, verbose_name='用户性别')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='联系方式')),
                ('address', models.CharField(default='', max_length=255, verbose_name='地址')),
                ('user_img', models.ImageField(upload_to='user/%Y', verbose_name='头像')),
                ('user_status', models.IntegerField(choices=[(1, '活跃'), (2, '禁用')], default=1, verbose_name='用户状态')),
            ],
        ),
    ]
