# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-07 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_name', models.CharField(default='', max_length=30, verbose_name='申请人名称')),
                ('sce_id', models.CharField(default='', max_length=255, verbose_name='场景识别码')),
                ('apply_detail', models.TextField(default='', verbose_name='来访原由')),
                ('apply_Inc', models.CharField(default='', max_length=255, verbose_name='所属公司')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2019, 7, 7, 23, 8, 50, 945506), null=True, verbose_name='来访时间')),
                ('end_time', models.DateTimeField(default=datetime.datetime(2019, 7, 7, 23, 8, 50, 945506), null=True, verbose_name='离开时间')),
            ],
        ),
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_name', models.CharField(default='', max_length=30, verbose_name='审核人名称')),
            ],
        ),
    ]
