# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-07 23:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verify',
        ),
        migrations.RemoveField(
            model_name='access',
            name='apply_Inc',
        ),
        migrations.AddField(
            model_name='access',
            name='apply_phone',
            field=models.CharField(default='', max_length=20, verbose_name='联系方式'),
        ),
        migrations.AddField(
            model_name='access',
            name='apply_status',
            field=models.IntegerField(choices=[(1, '未审核'), (2, '已审核')], default=1, verbose_name='用户状态'),
        ),
        migrations.AddField(
            model_name='access',
            name='visit_peo',
            field=models.TextField(default='', verbose_name='随行人员'),
        ),
        migrations.AlterField(
            model_name='access',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 7, 23, 27, 22, 505507), null=True, verbose_name='离开时间'),
        ),
        migrations.AlterField(
            model_name='access',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 7, 23, 27, 22, 505507), null=True, verbose_name='来访时间'),
        ),
    ]
