# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-05 14:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depname', models.CharField(default='', max_length=60, verbose_name='部门名称')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2019, 7, 5, 14, 17, 23, 184535), null=True)),
                ('person_num', models.IntegerField(default=0)),
                ('depstatus', models.IntegerField(choices=[(1, '解冻状态'), (2, '冻结状态')], default=1)),
                ('detail', models.TextField(default='', verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='学生姓名')),
                ('age', models.IntegerField(default=0, verbose_name='学生年龄')),
            ],
        ),
    ]
