# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-06 17:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_user', '0003_auto_20190706_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 17, 6, 28, 164792), null=True),
        ),
    ]
