# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-07 18:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_user', '0004_auto_20190706_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 7, 18, 1, 10, 226674), null=True),
        ),
    ]
