# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-07 23:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_user', '0006_auto_20190707_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 7, 23, 27, 22, 502507), null=True),
        ),
    ]
